language: generic
sudo: required

services:
  - docker

before-install:
  - docker build -t smetca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smetca/docker-react npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-026197526383"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


# docker run -e CI=true smetca/docker-react npm test