language: generic
sudo: required

services:
  - docker

before-install:
  - docker build -t smetca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smetca/docker-react npm test -- --coverage

# docker run -e CI=true smetca/docker-react npm test